name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Loguearse en Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 4. Construir la imagen Docker y etiquetarla
    - name: Build Docker image
      run: |
        docker build -t rosariowrobel/mi-app:${{ github.sha }} -t rosariowrobel/mi-app:latest .

    # 5. Publicar la imagen en Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push rosariowrobel/mi-app:${{ github.sha }}
        docker push rosariowrobel/mi-app:latest
